### ISSUE TITLE
Visualization failure at specific parameters with "NaN" errors

### ISSUE THREAD

**Issue by exfool** [tensorflow/playground#5] opened 2016-04-13 18:30 UTC
![tensorflow_visualization_fail](https://cloud.githubusercontent.com/assets/5960272/14504766/d40bab4a-01be-11e6-8835-fca4dd6d4ff0.jpg)

**Comment by dsmilkov** [comment] 2016-04-14 14:48
Duplicate of #3

**Closed by dsmilkov** 2016-04-14 14:48 UTC
